paths:
  /products/:
    get:
      summary: Oobtener todos los productos"
      tags:
        - Products
      responses:
        "200":
          description: "Devuelve los productos"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: "Error interno del servido"
    post:
      summary: "Agregar un producto"
      tags:
        - Products
      responses:
        "200":
          description: "Crea un nuevo producto"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "500":
          description: "Error interno del servido"
  /products/{id} :
    get:
      summary: Obtener un producto por su id 
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: "Parametro para especicar el id del producto"
          schema:
            type: string
      responses:
        "200":
          description: Devuelve un producto que coincida con el id ingresado
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "500":
          description: "Error interno del servido"  

    put:
      summary: Actualizar un producto por su id
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: "Parametro para especicar el id del producto a actualizar"
          schema:
            type: string
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#components/schemas/updateProduct"
      responses:
        "200":
          description: "Actualiza un producto que coincida con el id ingresado"
        "500":
          description: "Error interno del servido"  

    delete:
      summary: "Eliminar un producto por su id"
      tags:
        - Products
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: "Parametro para especicar el id del producto a eliminar"
          schema:
            type: string
      responses:
        "200":
          description: "Elimina el producto que coincida con el id ingresado"
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Product"
        "500":
          description: "Error interno del servido"            
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: id autogenerado por mongo
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        code:
          type: string
          description: codigo del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: number
          description: stock del producto
        owner:
          type: string
          description: id o email del dueño del producto
      example:
        _id: ObjectId("651cae668a422c50831b4343")
        title: "Papas fritas"
        description: "Papas fritas 300gr"
        code: 764c442a-2e24-42e9-8e7b-3b4ed69ae50c
        category: "Snacks"
        price: 450
        stock: 130
        owner: email.213@hotmail.com
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: number
          description: stock del producto
      example:
        title: "Agua"
        description: "Agua 2L"
        category: "Bebidas"
        price: 400
        stock: 200
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: titulo del producto
        description:
          type: string
          description: descripcion del producto
        category:
          type: string
          description: categoria del producto
        price:
          type: number
          description: precio del producto
        stock:
          type: number
          description: stock del producto
      example:
        title: "Harina"
        description: "Harina 0000 1kg"
        category: "Alimentos"
        price: 300
        stock: 80
    securitySchemes:
      cookieAuth:
        type: apiKey
        in: cookie
        name: Codercookie
